CC=cc

# Section 9.0.
run-program01: program01-basic-priority-queue-adt.c
	@cat $<

run-exercise01: exercise01.md
	@cat $<
run-exercise03-04: exercise03-04.md
	@cat $<

# Section 9.1. Elementary Implementation
run-program02: program02-array-implementation-of-a-priority-queue.c
	@cat $<

# Section 9.2. Heap Data Structure

# Section 9.3. Algorithms on Heaps
