CC=gcc

figure3: figure3-quickfind-example.c
	$(CC) -o $@ $<
figure6: figure6-quickunion-example.c
	$(CC) -o $@ $<

clean:
	$(RM) figure3 figure6
	$(RM) program1-quickfind program2-quickunion program3-weighted-quickunion program4-weighted-quickunion-with-path-compression-by-halving
	$(RM) exercise04 exercise05 exercise06 exercise07 exercise08 exercise14 exercise15 exercise16 exercise17
